apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: go0216
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go0216 
  name: go0216
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: go0216
    weight: 100 
